# Generated by Django 2.0 on 2018-10-31 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('surname', models.CharField(max_length=40)),
                ('phone', models.IntegerField(default='0803312244')),
                ('userid', models.IntegerField(default=0)),
                ('lng', models.FloatField(blank=True, default=0, max_length=100)),
                ('lat', models.FloatField(blank=True, default=0, max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('address', models.TextField(default=0)),
                ('panicked', models.DateField(auto_now_add=True)),
                ('is_panicking', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ('slug',),
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lng', models.FloatField(blank=True, default=0, max_length=100)),
                ('lat', models.FloatField(blank=True, default=0, max_length=100)),
                ('speed', models.FloatField(blank=True, default=0, max_length=100)),
                ('accuracy', models.FloatField(blank=True, default=0, max_length=100)),
                ('address', models.TextField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Customer')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
